### ISSUE TITLE
oracle metadata load error

### ISSUE THREAD

**Issue by happyBluebirds** [apache/shardingsphere#15399]
### Which version of ShardingSphere did you use?
5.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
    <version>5.0.0</version>
</dependency>
### Expected behavior
load success
### Actual behavior
load error
### Reason analyze (If you can)
![image](https://user-images.githubusercontent.com/20511657/153808329-1ccbb555-1a5b-4387-bb93-f52ffa4c082f.png)

resultSet.getString("COLLATION") can be null，only columns with character data types can not be null.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
tables config any oracle table with not only character data type.

### Example codes for reproduce this issue (such as a github link).
![image](https://user-images.githubusercontent.com/20511657/153808034-f4463d7e-ba11-4dca-96cf-e35eacf358f2.png)
actual-data-nodes: master.LOG_TEST,run and  will show java.lang.NullPointerException

**Comment by strongduanmu** [comment]
Hi @happyBluebirds, thank you for your feedback, can you try latest 5.1.0 version? I think this bug has been fixed.

**Comment by happyBluebirds** [comment]
> 

![image](https://user-images.githubusercontent.com/20511657/153811115-6ab45c26-9265-409a-ad7b-ecb4de85154d.png)
I hope so, but the latest version is still 5.0.0.

**Comment by strongduanmu** [comment]
@happyBluebirds Now  5.1.0 is being released, you can use the code of 5.1.0 tag for testing.

**Comment by happyBluebirds** [comment]
> 

![image](https://user-images.githubusercontent.com/20511657/153838795-a936ba9f-b91f-4ef8-be86-b6c25cb0b5ab.png)

I downloaded the tag of 5.1.0. After local compilation, this problem was not solved.

**Comment by happyBluebirds** [comment]
![image](https://user-images.githubusercontent.com/20511657/153839128-8d732dd8-b157-440d-ac86-53119b7dc789.png)

**Comment by strongduanmu** [comment]
@tuichenchuxin Can you help check this issue?

**Comment by tuichenchuxin** [comment]
@happyBluebirds This exception occurs because of oracle version.
This exception will not affect the use of shardingSphere.
Because we have default loader to load metadata, when dialect loader has exception.
By the way , can you help to solve this problem by submitting a pr?

**Comment by terrymanu** [comment]
The version is out of service, please try new version
