### ISSUE TITLE
Sharding-jdbc execute sql, in(x,x,x) performance issues

### ISSUE THREAD

**Issue by duanbin0414** [apache/shardingsphere#3366]
version 4.0.0-RC1
![image](https://user-images.githubusercontent.com/50389867/67537466-2098d300-f70e-11e9-93ec-6ad0a23fae2c.png)
when execute 
 Condition condition = new Condition(User.class);
        ArrayList<String> billCodes = new ArrayList<>();
        billCodes.add("13");
        billCodes.add("14");
        condition.createCriteria().andIn("id", billCodes);
 only need to query two tables from two database, but actually calculate four tableUnits to execue.
 two additional tables were queried.

Is there a problem with this performance loss?
Whether the data query table relationship can be maintained and executed precisely?

**Comment by sunbufu** [comment]
Please show your configuration and SQL.

**Comment by duanbin0414** [comment]
whether there is a dingding discussion group can pull me?

**Comment by duanbin0414** [comment]
I'm execute own packaged after sharding, tk.mybatis.mapper implementation of an in query.

**Comment by tanzaole** [comment]
I found the same problem, is there a solution?

**Comment by sunbufu** [comment]
Can you create a demo to reproduce this issue?

**Comment by duanbin0414** [comment]
> Can you create a demo to reproduce this issue?

       ArrayList<String> billCodes = new ArrayList<>();
        billCodes.add("13");
        billCodes.add("14");

        Example example = new Example(User.class);
        example.createCriteria().andIn("id", billCodes);
        List<User> users = userMapper3.selectByExample(example);

**Comment by ygycomon** [comment]
Same issue with me.

I copy the demo code from https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/usage/sharding/.
The <Rule Configuration Based on Java> which is the simplest way to run.

SQL:select * from test_table where user_id in (1, 2, 3) 

I use Wireshark to get all requests, it shows Shardingsphere sends 9 Query Requests to DB.
select * from act_money_account_1 where user_id in (1, 2, 3)
select * from act_money_account_1 where user_id in (1, 2, 3)
select * from act_money_account_1 where user_id in (1, 2, 3)
select * from act_money_account_2 where user_id in (1, 2, 3)
select * from act_money_account_2 where user_id in (1, 2, 3)
select * from act_money_account_2 where user_id in (1, 2, 3)
select * from act_money_account_3 where user_id in (1, 2, 3)
select * from act_money_account_3 where user_id in (1, 2, 3)
select * from act_money_account_3 where user_id in (1, 2, 3)

Code:
`
Map<String, DataSource> dataSourceMap = new HashMap<>();
BasicDataSource dataSource1 = new BasicDataSource();
dataSource1.setDriverClassName("com.mysql.jdbc.Driver");
dataSource1.setUrl("jdbc:mysql://10.0.8.2:3306/test_00");
dataSource1.setUsername("test");
dataSource1.setPassword("");
dataSourceMap.put("ds0", dataSource1);

BasicDataSource dataSource2 = new BasicDataSource();
dataSource2.setDriverClassName("com.mysql.jdbc.Driver");
dataSource2.setUrl("jdbc:mysql://10.0.8.2:3306/test_00");
dataSource2.setUsername("test");
dataSource2.setPassword("");
dataSourceMap.put("ds1", dataSource2);

BasicDataSource dataSource3 = new BasicDataSource();
dataSource2.setDriverClassName("com.mysql.jdbc.Driver");
dataSource2.setUrl("jdbc:mysql://10.0.8.2:3306/test_02");
dataSource2.setUsername("test");
dataSource2.setPassword("");
dataSourceMap.put("ds2", dataSource2);

TableRuleConfiguration orderTableRuleConfig = new TableRuleConfiguration("act_money_account","ds${0..2}.test${0..9}");

orderTableRuleConfig.setDatabaseShardingStrategyConfig(new InlineShardingStrategyConfiguration("user_id", "ds${user_id % 3}"));
orderTableRuleConfig.setTableShardingStrategyConfig(new InlineShardingStrategyConfiguration("user_id", "test_${user_id % 10}"));

ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
shardingRuleConfig.getTableRuleConfigs().add(orderTableRuleConfig);

Properties p = new Properties();
p.setProperty("sql.show", "true");
DataSource dataSource = ShardingDataSourceFactory.createDataSource(dataSourceMap, shardingRuleConfig, p);
`

This issue can cause serious problem in PRD environment! Is there any solution to this?

**Comment by ygycomon** [comment]
> Same issue with me.
> 
> I copy the demo code from https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/usage/sharding/.
> The which is the simplest way to run.
> 
> SQL:select * from test_table where user_id in (1, 2, 3)
> 
> I use Wireshark to get all requests, it shows Shardingsphere sends 9 Query Requests to DB.
> select * from act_money_account_1 where user_id in (1, 2, 3)
> select * from act_money_account_1 where user_id in (1, 2, 3)
> select * from act_money_account_1 where user_id in (1, 2, 3)
> select * from act_money_account_2 where user_id in (1, 2, 3)
> select * from act_money_account_2 where user_id in (1, 2, 3)
> select * from act_money_account_2 where user_id in (1, 2, 3)
> select * from act_money_account_3 where user_id in (1, 2, 3)
> select * from act_money_account_3 where user_id in (1, 2, 3)
> select * from act_money_account_3 where user_id in (1, 2, 3)
> 
> Code:
> `
> Map<String, DataSource> dataSourceMap = new HashMap<>();
> BasicDataSource dataSource1 = new BasicDataSource();
> dataSource1.setDriverClassName("com.mysql.jdbc.Driver");
> dataSource1.setUrl("jdbc:mysql://127.0.0.1:3306/test_00");
> dataSource1.setUsername("test");
> dataSource1.setPassword("");
> dataSourceMap.put("ds0", dataSource1);
> 
> BasicDataSource dataSource2 = new BasicDataSource();
> dataSource2.setDriverClassName("com.mysql.jdbc.Driver");
> dataSource2.setUrl("jdbc:mysql://127.0.0.1:3306/test_00");
> dataSource2.setUsername("test");
> dataSource2.setPassword("");
> dataSourceMap.put("ds1", dataSource2);
> 
> BasicDataSource dataSource3 = new BasicDataSource();
> dataSource2.setDriverClassName("com.mysql.jdbc.Driver");
> dataSource2.setUrl("jdbc:mysql://127.0.0.1:3306/test_02");
> dataSource2.setUsername("test");
> dataSource2.setPassword("");
> dataSourceMap.put("ds2", dataSource2);
> 
> TableRuleConfiguration orderTableRuleConfig = new TableRuleConfiguration("act_money_account","ds${0..2}.test${0..9}");
> 
> orderTableRuleConfig.setDatabaseShardingStrategyConfig(new InlineShardingStrategyConfiguration("user_id", "ds${user_id % 3}"));
> orderTableRuleConfig.setTableShardingStrategyConfig(new InlineShardingStrategyConfiguration("user_id", "test_${user_id % 10}"));
> 
> ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
> shardingRuleConfig.getTableRuleConfigs().add(orderTableRuleConfig);
> 
> Properties p = new Properties();
> p.setProperty("sql.show", "true");
> DataSource dataSource = ShardingDataSourceFactory.createDataSource(dataSourceMap, shardingRuleConfig, p);
> `
> 
> This issue can cause serious problem in PRD environment! Is there any solution to this?

BTW, I am with newest version: 4.0.0-RC2

**Comment by yanyzy** [comment]
Hi @ygycomon , i think this is due to your sharding rules.
```
orderTableRuleConfig.setDatabaseShardingStrategyConfig(new InlineShardingStrategyConfiguration("user_id", "ds${user_id % 3}"));
orderTableRuleConfig.setTableShardingStrategyConfig(new InlineShardingStrategyConfiguration("user_id", "test_${user_id % 10}"));
```
`user_id in (1, 2, 3)`  will route to 3 databases and 3 tables, so it is  9 query requests.

**Comment by ygycomon** [comment]
> ink this is due to your shardi

Thanks for you reply. How can I config to make Shardingsphere send only 3 query requests?  The data locates in three certain tables, it useless to send extra 6 query requests to DB which do not contains data. BTW, I shard my data into 100 DBs * 10 Tables, it costs serious problem in my situation

**Comment by ygycomon** [comment]
https://shardingsphere.apache.org/document/current/en/features/sharding/principle/route/
However, Shardingsphere  document says if SQL is
`
SELECT * FROM t_order WHERE order_id IN (1, 2);
`
The route result will be:
`
SELECT * FROM t_order_0 WHERE order_id IN (1, 2);
SELECT * FROM t_order_1 WHERE order_id IN (1, 2);
`
The original logical SQL is split into 2 query requests instead of 4 query requests as above.

So I am quite wondering if I am wrong with config or this is a BUG or this is a designed feature?

**Comment by yanyzy** [comment]
@ygycomon 
Maybe you can use ` Standard Sharding Strategy`, refer to https://shardingsphere.apache.org/document/current/en/features/sharding/concept/sharding/,  and 
here are some examples https://github.com/apache/incubator-shardingsphere-example

**Comment by duanbin0414** [comment]
> @ygycomon
> Maybe you can use ` Standard Sharding Strategy`, refer to https://shardingsphere.apache.org/document/current/en/features/sharding/concept/sharding/, and
> here are some examples https://github.com/apache/incubator-shardingsphere-example

I used Standard Sharding Strategy, found this proplem.

**Comment by ygycomon** [comment]
> @ygycomon
> Maybe you can use ` Standard Sharding Strategy`, refer to https://shardingsphere.apache.org/document/current/en/features/sharding/concept/sharding/, and
> here are some examples https://github.com/apache/incubator-shardingsphere-example

I switch into Standard Sharding Strategy, but I fail. Sends 9 query request to DB again. 

`
StandardShardingStrategyConfiguration stdDBConfig = new StandardShardingStrategyConfiguration("user_id", new PreciseShardingAlgorithm() {
			@Override
			public String doSharding(Collection collection, PreciseShardingValue preciseShardingValue) {
				Integer index = Long.valueOf(preciseShardingValue.getValue().toString()).intValue() % 3;
				return "ds" + index;
			}
		});

StandardShardingStrategyConfiguration stdTableConfig = new StandardShardingStrategyConfiguration("user_id", new PreciseShardingAlgorithm() {
			@Override
			public String doSharding(Collection collection, PreciseShardingValue preciseShardingValue) {
				Integer index = Long.valueOf(preciseShardingValue.getValue().toString()).intValue() % 10;
				return "test_" + index;
			}
		});
orderTableRuleConfig.setDatabaseShardingStrategyConfig(stdDBConfig);
orderTableRuleConfig.setTableShardingStrategyConfig(stdTableConfig);
`

Logic SQL:
`
select * from test where user_id in (1, 2, 3)
`
result:
`
14:36:57.798 [main] INFO ShardingSphere-SQL - Actual SQL: ds0 ::: select * from test_1 where user_id in (1, 2, 3)
14:36:57.798 [main] INFO ShardingSphere-SQL - Actual SQL: ds0 ::: select * from test_2 where user_id in (1, 2, 3)
14:36:57.798 [main] INFO ShardingSphere-SQL - Actual SQL: ds0 ::: select * from test_3 where user_id in (1, 2, 3)
14:36:57.798 [main] INFO ShardingSphere-SQL - Actual SQL: ds1 ::: select * from test_1 where user_id in (1, 2, 3)
14:36:57.798 [main] INFO ShardingSphere-SQL - Actual SQL: ds1 ::: select * from test_2 where user_id in (1, 2, 3)
14:36:57.798 [main] INFO ShardingSphere-SQL - Actual SQL: ds1 ::: select * from test_3 where user_id in (1, 2, 3)
14:36:57.798 [main] INFO ShardingSphere-SQL - Actual SQL: ds2 ::: select * from test_1 where user_id in (1, 2, 3)
14:36:57.798 [main] INFO ShardingSphere-SQL - Actual SQL: ds2 ::: select * from test_2 where user_id in (1, 2, 3)
14:36:57.798 [main] INFO ShardingSphere-SQL - Actual SQL: ds2 ::: select * from test_3 where user_id in (1, 2, 3)
`

**Comment by duanbin0414** [comment]
> > ink this is due to your shardi
> 
> Thanks for your reply. How can I config to make Shardingsphere send only 3 query requests? The data locates in three certain tables, it's useless to send extra 6 query requests to DB which does not contain data. BTW, I shard my data into 100 DBs * 10 Tables, it costs serious problem in my situation

Welcome to discuss, [https://blog.csdn.net/D_19901719576/article/details/102925945]( https://blog.csdn.net/D_19901719576/article/details/102925945)

**Comment by duanbin0414** [comment]
> Hi @ygycomon , i think this is due to your sharding rules.
> 
> ```
> orderTableRuleConfig.setDatabaseShardingStrategyConfig(new InlineShardingStrategyConfiguration("user_id", "ds${user_id % 3}"));
> orderTableRuleConfig.setTableShardingStrategyConfig(new InlineShardingStrategyConfiguration("user_id", "test_${user_id % 10}"));
> ```
> 
> `user_id in (1, 2, 3)` will route to 3 databases and 3 tables, so it is 9 query requests.

Welcome to discuss, https://blog.csdn.net/D_19901719576/article/details/102925945

**Comment by KomachiSion** [comment]
@duanbin0414, Thanks for your discuss and article.

In fact, problem for routing to additional nodes when the database and table sharding column are the same one, community has been known, you can search more issues about this problem like #2193 .

We design current routeEngine to calculate database sharding columns and table sharding columns independent. Because the shardingRule are different for each user.
The design can only call one time database sharding algorithm and table sharding algorithm. And users can think about and configure database sharding algorithm and table sharding algorithm independent. Especially in different database and table sharding column.

In your article, I see a base solution, but this solution only can solve the situation that sharding columns are same one and the numbers of database and table are equals. I think it is very customized. Do you have a more complete solution?

We can discuss in this issue.

**Comment by duanbin0414** [comment]
> @duanbin0414, Thanks for your discuss and article.
> 
> In fact, problem for routing to additional nodes when the database and table sharding column are the same one, community has been known, you can search more issues about this problem like #2193 .
> 
> We design current routeEngine to calculate database sharding columns and table sharding columns independent. Because the shardingRule are different for each user.
> The design can only call one time database sharding algorithm and table sharding algorithm. And users can think about and configure database sharding algorithm and table sharding algorithm independent. Especially in different database and table sharding column.
> 
> In your article, I see a base solution, but this solution only can solve the situation that sharding columns are same one and the numbers of database and table are equals. I think it is very customized. Do you have a more complete solution?
> 
> We can discuss in this issue.

First, I do assume that there are the same number of tables in each database. I refer to the official configuration example and think it is consistent with the official one.
![image](https://user-images.githubusercontent.com/50389867/68646398-07898200-0556-11ea-9376-7b91e6f3b12c.png)

Although the actual name of the table in my database is different. For example: ds0:user0,user1. ds1:user2,user3. Although loading the configured data node is inconsistent with the actual situation, it does not affect the correctness of my data routing. Because through my custom database and table algorithm I will not route to a nonexistent node. For example: ds0:user2,user3, but according to the existing official logic these errors will occur.

According to my understanding, whether the key of database and database table is the same or not is only related to the specific table and database sorting algorithm, so it will not affect my routing logic.

According to my understanding, the most likely problem between the official configuration and me is that if multiple data are configured, but only part of a table is designed, it needs to be configured in order.
![image](https://user-images.githubusercontent.com/50389867/68646797-1f153a80-0557-11ea-897a-2c401493c08a.png)
![image](https://user-images.githubusercontent.com/50389867/68646833-3bb17280-0557-11ea-8e84-fa860d98fbae.png)
databases configuration order needs to be adjusted on its own.or combine by multiple $->{ expression }.

Welcome to point out mistakes.

**Comment by KomachiSion** [comment]
> First, I do assume that there are the same number of tables in each database. I refer to the official configuration example and think it is consistent with the official one.

Sorry, I means your solution only support the database route result number equals to table route result. If the results are not equals, there are some result will be dropped.
BTW, `ds${0..1}.t_order_item${0..1}` is 2 databases and 4 tables(2 tables in each database).

> but according to the existing official logic these errors will occur.

The problem has been fixed in 4.0.0-RC3 which has been in release vote step, detail in #2193.

> According to my understanding, whether the key of database and database table is the same or not is only related to the specific table and database sorting algorithm, so it will not affect my routing logic.

Sorry, I think it has some different in same sharding column and different columns.
Because different sharding columns means the two algorithm are independent fully, but for same sharding column, they may has some related in database and table.

> it needs to be configured in order. databases configuration order needs to be adjusted on its own.or combine by multiple $->{ expression }.

I don't get why users need to configure databases and tables by order except binding-table.

At last, I suggest you put a more detail and complete design, current information is too dispersed to  understand. I only can get one custom fix -- try route with your logic, if result database and table numbers are equal, then return, otherwise use origin route?

**Comment by Ah39** [comment]
2017-2019，2.x to 4.x  The bug   not fixed
https://github.com/apache/incubator-shardingsphere/issues/286

**Comment by kimmking** [comment]
In my recent tests, sharding-jdbc will optimize datanode number but do not cut the values in ‘in clause’.

For example, actual tables is test0...3, and condition is id % 4, when executing sql:
> select * from test where id in (100,101)

Actual sqls are:
> select * from test00 where id in (100,101)
> select * from test01 where id in (100,101)

Table data nodes are cut from 4 to 2 now.

**Comment by BruceZhangXL** [comment]
> In my recent tests, sharding-jdbc will optimize datanode number but do not cut the values in ‘in clause’.
> 
> For example, actual tables is test0...3, and condition is id % 4, when executing sql:
> 
> > select * from test where id in (100,101)
> 
> Actual sqls are:
> 
> > select * from test00 where id in (100,101)
> > select * from test01 where id in (100,101)
> 
> Table data nodes are cut from 4 to 2 now.

which version?

**Comment by BruceZhangXL** [comment]
![image](https://user-images.githubusercontent.com/10344508/83850201-298d6080-a743-11ea-8d18-cde4ad7b298e.png)

供参考

**Comment by kimmking** [comment]
@BruceZhangXL do you submit a pr and describe your fixture?

**Comment by BruceZhangXL** [comment]
> @BruceZhangXL do you submit a pr and describe your fixture?

not yet,the logic is right. u can reference to your inner version

**Comment by xunki** [comment]
I have the same problem,the routing result is the Cartesian product of the library and the table
