### ISSUE TITLE
RangeShardingAlgorithm   Range subquery   ClassCastException

### ISSUE THREAD

**Issue by lyricsqq** [apache/shardingsphere#3500]
Version number 4.0.0-RC2：
When I execute the following SQL：
select count(0) from ( select devId from t_check_task where status=1 and executeTime BETWEEN '2018' and '2019' ) b

The exception is generated in the parsingsqlrouter class in isSameShardingCondition
Cause: java.lang.ClassCastException: org.apache.shardingsphere.core.strategy.route.value.RangeRouteValue cannot be cast to org.apache.shardingsphere.core.strategy.route.value.ListRouteValue]

**Comment by terrymanu** [comment]
Can you change the title for search friendly?

**Comment by terrymanu** [comment]
I think the title still not for search friendly

**Comment by KomachiSion** [comment]
Do you use 4.0.0-RC2 release version?

I think the problem is reference #2613 . Should be fixed in 4.0.0-RC2 release.

**Comment by lyricsqq** [comment]
version is  4.0.0-RC2
I introduced the following Maven configuration according to the official documents

        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>4.0.0-RC2</version>
        </dependency>

        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-namespace</artifactId>
            <version>4.0.0-RC2</version>
        </dependency>

**Comment by lyricsqq** [comment]
I use the range fragmentation algorithm instead of the composite fragmentation algorithm

**Comment by KomachiSion** [comment]
@lyricsqq Can you provide your full sharding configuration, or push your demo code to GitHub?

Can help us to locate the problem.

**Comment by lyricsqq** [comment]
The exception occurs in the method of the following screenshot of the parsingsqlrouter class. And I looked at the 4.0.0-rc3 code, and I think this problem should still exist
![Uploading image.png…]()

**Comment by lyricsqq** [comment]
The following logical table of springboot configuration is the configuration when I have problems commented out by t ﹣ check ﹣ task. I now use the forced sharding to meet the needs of。
spring:
  logpath: /home/logs/
  main:
    allow-bean-definition-overriding: true
  application:
    name: web
  shardingsphere:
    datasource:
      names: master
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: wbxtest
        jdbcUrl: jdbc:mysql://xxxxxxx:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    sharding:
      tables:
        t_check_task:
          actual-data-nodes: master.t_check_task_$->{2017..2020}$->{['01','02','03','04','05','06','07','08','09','10','11','12']}
          key-generator:
            column: id
            type: SNOWFLAKE
          table-strategy:
            hint:
              algorithm-class-name: com.wontex.inquiry.shard.Hint
          databaseStrategy:
            hint:
              algorithm-class-name: com.wontex.inquiry.shard.Hint
          #  standard:
          #    sharding-column: executeTime
          #    rangeAlgorithmClassName: com.wontex.inquiry.shard.Range
          #    precise-algorithm-class-name: com.wontex.inquiry.shard.Precise
        t_base_defect_log:
          actual-data-nodes: master.t_base_defect_log_$->{2017..2020}$->{['01','02','03','04','05','06','07','08','09','10','11','12']}
          key-generator:
            column: id
            type: SNOWFLAKE
          table-strategy:
            inline:
              sharding-column: createdTime
              algorithm-expression: t_base_defect_log_$->{ if(createdTime!=null){ return createdTime.format("yyyyMM")}}
        t_base_defect_operate:
          actual-data-nodes: master.t_base_defect_operate_$->{2017..2020}$->{['01','02','03','04','05','06','07','08','09','10','11','12']}
          key-generator:
            column: id
            type: SNOWFLAKE
          table-strategy:
            inline:
              sharding-column: createdTime
              algorithm-expression: t_base_defect_operate_$->{ if(createdTime!=null){ return createdTime.format("yyyyMM")}}
        t_base_defect:
          actual-data-nodes: master.t_base_defect_$->{2017..2020}$->{['01','02','03','04','05','06','07','08','09','10','11','12']}
          key-generator:
            column: id
            type: SNOWFLAKE
          table-strategy:
            inline:
              sharding-column: createdTime
              algorithm-expression: t_base_defect_$->{ if(createdTime!=null){ return createdTime.format("yyyyMM")}}
    props:
      sql:
        show: true


The implementation classes of fragmentation algorithm are as follows。

package com.wontex.inquiry.shard;

import com.alibaba.fastjson.JSON;
import com.google.common.collect.Lists;
import com.google.common.collect.Sets;
import com.wontex.core.utils.DateUtil;
import org.apache.shardingsphere.api.sharding.standard.RangeShardingAlgorithm;
import org.apache.shardingsphere.api.sharding.standard.RangeShardingValue;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Set;

public class Range implements RangeShardingAlgorithm<Date> {
    Logger logger = LoggerFactory.getLogger(Range.class);

    @Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, RangeShardingValue<Date> shardingValue) {
        Date start = shardingValue.getValueRange().lowerEndpoint();
        Date end = shardingValue.getValueRange().upperEndpoint();
        int cr = DateUtil.getMonthsBetween(start, end);
        List<String> das = Lists.newArrayList();
        for (int i = 0; i < cr; i++) {
            Date date = DateUtil.addMonths(start, i + 1);
            das.add(DateUtil.formatDate(date, "yyyyMM"));
        }
        // 获取数据
        Set<String> tables = Sets.newTreeSet();
        //符合条件的表
        for (String da : das) {
            for (String target : availableTargetNames) {
                if (target.contains(da)) {
                    tables.add(target);
                }
            }
        }
        logger.info("目标表:" + JSON.toJSONString(tables));
        return tables;
    }
}

**Comment by lyricsqq** [comment]
The configuration file and implementation class are as follows. Because the attachment does not support suffix, I will change the file suffix to txtl
[application-test.txt](https://github.com/apache/incubator-shardingsphere/files/3834658/application-test.txt)

[Range.txt](https://github.com/apache/incubator-shardingsphere/files/3834662/Range.txt)

**Comment by lyricsqq** [comment]
I don't know how to get the demo on github running for you.Can I give you a link to my demo warehouse

**Comment by KomachiSion** [comment]
> I don't know how to get the demo on github running for you.Can I give you a link to my demo warehouse

create repo in your GitHub. and push your demo code to the repo you create. Then copy the link to these.

your configuration may be enough, If you can provide your SQL will help us more.

**Comment by lyricsqq** [comment]
Later, I will create a demo to reproduce the problems I encountered in the project, which may take several hours. I will provide a code that fully replicates the problem you can run directly But my comment is Chinese because I am not good at English in China If the code needs to provide English comments, you can let me know

**Comment by KomachiSion** [comment]
> Later, I will create a demo to reproduce the problems I encountered in the project, which may take several hours. I will provide a code that fully replicates the problem you can run directly But my comment is Chinese because I am not good at English in China If the code needs to provide English comments, you can let me know

Thanks, English comments will be better. you can provide your SQL first, if we can't reproduce your problem, we will need your demo code later.

**Comment by lyricsqq** [comment]
Here is the demo code link address。
https://github.com/lyricsqq/shardingerror.git

You can start it and visit it through the following link。

http://localhost:8080/swagger-ui.html

**Comment by KomachiSion** [comment]
Sorry I use your code execute `getColumnarStatistics`

the exception is
```
Failed to convert property value of type 'java.lang.String' to required type 'java.util.Date' for property 'startTime'; 
nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@io.swagger.annotations.ApiModelProperty 
@org.springframework.format.annotation.DateTimeFormat java.util.Date] for value '2019-10-11'; 
nested exception is java.lang.IllegalArgumentException: Parse attempt failed for value [2019-10-11]
```

**Comment by lyricsqq** [comment]
I changed the code and it worked The start time and end time need to be more than 2 months before the error effect can be seen。
eg：

startTime = 2019-01-01
endTime = 2019-04-05

**Comment by lyricsqq** [comment]
Please remove the code at the pull, thank you. It will work

**Comment by KomachiSion** [comment]
The problem has reproduced, Thanks your reply.

The bug will fixed with #3187 .

Current version do not support subQuery with range and multiple shard nodes.

**Comment by lyricsqq** [comment]
Will it be fixed in 4.0.0-RC3? 4.0.0- when will RC3 be released。
I use the forced route hint shard. Is there also the problem of not being able to route to multiple tables

**Comment by KomachiSion** [comment]
> Will it be fixed in 4.0.0-RC3? 4.0.0- when will RC3 be released。
> I use the forced route hint shard. Is there also the problem of not being able to route to multiple tables

4.0.0-RC3 has started vote, so the problem will be not fixed in 4.0.0-RC3.

**Comment by KomachiSion** [comment]
pending reason: need to fix with #3187 together.

**Comment by Ltyro** [comment]
so...has it been fixed?

**Comment by terrymanu** [comment]
The `5.0.0-beta` version supports federation engine which can process subquery, please try it, thank you.
