### ISSUE TITLE
Unsupported SQL of `CREATE TEMPORARY TABLE`

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#7134]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Support SQL:

```
CREATE TEMPORARY TABLE SalesSummary (
     product_name VARCHAR(50) NOT NULL
     , total_sales DECIMAL(12,2) NOT NULL DEFAULT 0.00
     , avg_unit_price DECIMAL(7,2) NOT NULL DEFAULT 0.00
     , total_units_sold INT UNSIGNED NOT NULL DEFAULT 0
);
```

### Actual behavior

```
[ERROR] 20:19:39.112 [ShardingSphere-Command-0] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
org.apache.shardingsphere.sql.parser.exception.SQLParsingException: Unsupported SQL of `CREATE TEMPORARY TABLE SalesSummary (
     product_name VARCHAR(50) NOT NULL
     , total_sales DECIMAL(12,2) NOT NULL DEFAULT 0.00
     , avg_unit_price DECIMAL(7,2) NOT NULL DEFAULT 0.00
     , total_units_sold INT UNSIGNED NOT NULL DEFAULT 0
)`
	at org.apache.shardingsphere.rdl.parser.engine.executor.RDLSQLParserExecutor.execute(RDLSQLParserExecutor.java:55)
	at org.apache.shardingsphere.rdl.parser.engine.engine.RDLSQLParserEngine.parse0(RDLSQLParserEngine.java:70)
	at org.apache.shardingsphere.rdl.parser.engine.engine.RDLSQLParserEngine.parse(RDLSQLParserEngine.java:52)
	at org.apache.shardingsphere.rdl.parser.engine.ShardingSphereSQLParserEngine.parse(ShardingSphereSQLParserEngine.java:47)
	at org.apache.shardingsphere.proxy.backend.text.TextProtocolBackendHandlerFactory.newInstance(TextProtocolBackendHandlerFactory.java:75)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:71)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:70)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:60)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:94)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:73)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tuohai666** [comment]
The exception caused by parser. @tristaZero , can you have a look?

**Comment by strongduanmu** [comment]
> The exception caused by parser. @tristaZero , can you have a look?

@tuohai666 @tristaZero I will check it. Now, I am checking the `create table statement` in MySQL DDL syntax and related to issue #6498.

**Comment by tuohai666** [comment]
@strongduanmu Thanks.

**Comment by strongduanmu** [comment]
@tuohai666 I found that this bug is related to [pr 5753](https://github.com/apache/shardingsphere/pull/5753). I have fixed it and added some related test cases.

**Comment by tuohai666** [comment]
@strongduanmu Can you double check do you really fix this issue?
I met this problem 4 hours ago.

**Comment by strongduanmu** [comment]
> @strongduanmu Can you double check did you really fix this issue?
> I met this problem 4 hours ago.

@tuohai666 I'm so sorry for my expression😂, the fixed [issue](https://github.com/apache/shardingsphere/pull/7142) has not been merged. After the PR is merged, you can test again.

**Comment by tuohai666** [comment]
@strongduanmu Get it. I have assigned this issue to you.

**Comment by lidonghai11** [comment]
![t](https://user-images.githubusercontent.com/66629133/92595317-c3325400-f2d6-11ea-8c0e-cd5c1142d073.png)
'TEMPORARY TABLE' doesn't work ,the error still exists.   The latest version of proxy that i test with.  @strongduanmu @tuohai666 @

**Comment by tuohai666** [comment]
@strongduanmu Please have a check.

**Comment by strongduanmu** [comment]
@lidonghai11 @tuohai666 Hello, you need to configure the table `SalesSummary` into the  sharding config, otherwise sharding-sphere does not know how to create the table ?
